/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IKtaGameChatInterface extends utils.Interface {
  functions: {
    "getAnnouncements()": FunctionFragment;
    "sendAnnouncement(string)": FunctionFragment;
    "sendMessage(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getAnnouncements"
      | "sendAnnouncement"
      | "sendMessage"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAnnouncements",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendAnnouncement",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAnnouncements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendAnnouncement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;

  events: {
    "Announcement(string)": EventFragment;
    "Message(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Announcement"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Message"): EventFragment;
}

export interface AnnouncementEventObject {
  message: string;
}
export type AnnouncementEvent = TypedEvent<[string], AnnouncementEventObject>;

export type AnnouncementEventFilter = TypedEventFilter<AnnouncementEvent>;

export interface MessageEventObject {
  user: string;
  message: string;
}
export type MessageEvent = TypedEvent<[string, string], MessageEventObject>;

export type MessageEventFilter = TypedEventFilter<MessageEvent>;

export interface IKtaGameChat extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IKtaGameChatInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAnnouncements(overrides?: CallOverrides): Promise<[string[]]>;

    sendAnnouncement(
      message: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendMessage(
      message: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getAnnouncements(overrides?: CallOverrides): Promise<string[]>;

  sendAnnouncement(
    message: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendMessage(
    message: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAnnouncements(overrides?: CallOverrides): Promise<string[]>;

    sendAnnouncement(
      message: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    sendMessage(
      message: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Announcement(string)"(message?: null): AnnouncementEventFilter;
    Announcement(message?: null): AnnouncementEventFilter;

    "Message(address,string)"(user?: null, message?: null): MessageEventFilter;
    Message(user?: null, message?: null): MessageEventFilter;
  };

  estimateGas: {
    getAnnouncements(overrides?: CallOverrides): Promise<BigNumber>;

    sendAnnouncement(
      message: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendMessage(
      message: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAnnouncements(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendAnnouncement(
      message: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendMessage(
      message: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
