/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKillThemAll__factory } from "./IKillThemAll__factory";
export { KillThemAll__factory } from "./KillThemAll__factory";
export { KtaToken__factory } from "./KtaToken__factory";
export { MultiCall__factory } from "./MultiCall__factory";
