/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KillThemAll__factory } from "./KillThemAll__factory";
export { KtaToken__factory } from "./KtaToken__factory";
