/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, ContractRunner } from "ethers";
import type { MultiCall, MultiCallInterface } from "../MultiCall";

const _abi = [
  {
    inputs: [],
    name: "CallFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "LengthNotMatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "targets",
        type: "address[]",
      },
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "multiCall",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class MultiCall__factory {
  static readonly abi = _abi;
  static createInterface(): MultiCallInterface {
    return new Interface(_abi) as MultiCallInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MultiCall {
    return new Contract(address, _abi, runner) as unknown as MultiCall;
  }
}
