/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as game from './game'
export type { game }
import type * as test from './test'
export type { test }
