/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKtaGameChat,
  IKtaGameChatInterface,
} from "../../../../contracts/game/chat/IKtaGameChat";

const _abi = [
  {
    inputs: [],
    name: "UserMustRegistered",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "Announcement",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "Message",
    type: "event",
  },
  {
    inputs: [],
    name: "getAnnouncements",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "sendAnnouncement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "sendMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IKtaGameChat__factory {
  static readonly abi = _abi;
  static createInterface(): IKtaGameChatInterface {
    return new utils.Interface(_abi) as IKtaGameChatInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKtaGameChat {
    return new Contract(address, _abi, signerOrProvider) as IKtaGameChat;
  }
}
