/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKtaGameChat__factory } from "./IKtaGameChat__factory";
export { KtaGameChat__factory } from "./KtaGameChat__factory";
