/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as passes from "./passes";
export type { passes };
export type { AKtaGamePass } from "./AKtaGamePass";
export type { IKtaGamePass } from "./IKtaGamePass";
export type { IKtaGamePassNft } from "./IKtaGamePassNft";
export type { KtaGamePassNft } from "./KtaGamePassNft";
