/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IKillThemAll } from "./IKillThemAll";
export type { KillThemAll } from "./KillThemAll";
export type { KtaToken } from "./KtaToken";
export type { MultiCall } from "./MultiCall";
export * as factories from "./factories";
export { IKillThemAll__factory } from "./factories/IKillThemAll__factory";
export { KillThemAll__factory } from "./factories/KillThemAll__factory";
export { KtaToken__factory } from "./factories/KtaToken__factory";
export { MultiCall__factory } from "./factories/MultiCall__factory";
