/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { KillThemAll } from "./KillThemAll";
export type { KtaToken } from "./KtaToken";
export * as factories from "./factories";
export { KillThemAll__factory } from "./factories/KillThemAll__factory";
export { KtaToken__factory } from "./factories/KtaToken__factory";
