/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  AKtaGamePass,
  AKtaGamePassInterface,
} from "../../../../contracts/game/pass/AKtaGamePass";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "phase",
        type: "uint256",
      },
    ],
    name: "claim",
    outputs: [
      {
        internalType: "bool",
        name: "result",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "userByAddress",
    outputs: [
      {
        internalType: "uint256",
        name: "health",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mana",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "energy",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "armor",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "int64",
            name: "_x",
            type: "int64",
          },
          {
            internalType: "int64",
            name: "_y",
            type: "int64",
          },
        ],
        internalType: "struct Coordinates.Coordinate",
        name: "coordinate",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "name",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "exp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "levelId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "referrer",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "townId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "joinBlock",
            type: "uint256",
          },
        ],
        internalType: "struct IKillThemAll.UserTownInfo",
        name: "townInfo",
        type: "tuple",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "_at",
                type: "uint256",
              },
            ],
            internalType: "struct Timers.BlockNumber",
            name: "getHealth",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_at",
                type: "uint256",
              },
            ],
            internalType: "struct Timers.BlockNumber",
            name: "getMana",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_at",
                type: "uint256",
              },
            ],
            internalType: "struct Timers.BlockNumber",
            name: "getEnergy",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_at",
                type: "uint256",
              },
            ],
            internalType: "struct Timers.BlockNumber",
            name: "revive",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_at",
                type: "uint256",
              },
            ],
            internalType: "struct Timers.BlockNumber",
            name: "teleport",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_at",
                type: "uint256",
              },
            ],
            internalType: "struct Timers.BlockNumber",
            name: "teleportToTown",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "_at",
                type: "uint256",
              },
            ],
            internalType: "struct Timers.BlockNumber",
            name: "prepareToAttack",
            type: "tuple",
          },
        ],
        internalType: "struct IKillThemAll.UserTimer",
        name: "timer",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "attack",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "defend",
            type: "uint256",
          },
        ],
        internalType: "struct IKillThemAll.UserCharPoint",
        name: "charPoint",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AKtaGamePass__factory {
  static readonly abi = _abi;
  static createInterface(): AKtaGamePassInterface {
    return new utils.Interface(_abi) as AKtaGamePassInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AKtaGamePass {
    return new Contract(address, _abi, signerOrProvider) as AKtaGamePass;
  }
}
