/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKtaGamePassNft,
  IKtaGamePassNftInterface,
} from "../../../../contracts/game/pass/IKtaGamePassNft";

const _abi = [
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "gamePassId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "contract IKtaGamePass",
            name: "pass",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "startBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endBlock",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "phaseLimits",
            type: "uint256[]",
          },
        ],
        internalType: "struct IKillThemAll.GamePass",
        name: "",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "userExp",
        type: "uint256",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IKtaGamePassNft__factory {
  static readonly abi = _abi;
  static createInterface(): IKtaGamePassNftInterface {
    return new Interface(_abi) as IKtaGamePassNftInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IKtaGamePassNft {
    return new Contract(address, _abi, runner) as unknown as IKtaGamePassNft;
  }
}
