/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKtaGamePass,
  IKtaGamePassInterface,
} from "../../../../contracts/game/pass/IKtaGamePass";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "phase",
        type: "uint256",
      },
    ],
    name: "claim",
    outputs: [
      {
        internalType: "bool",
        name: "result",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IKtaGamePass__factory {
  static readonly abi = _abi;
  static createInterface(): IKtaGamePassInterface {
    return new Interface(_abi) as IKtaGamePassInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IKtaGamePass {
    return new Contract(address, _abi, runner) as unknown as IKtaGamePass;
  }
}
