/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as passes from "./passes";
export { AKtaGamePass__factory } from "./AKtaGamePass__factory";
export { IKtaGamePass__factory } from "./IKtaGamePass__factory";
export { IKtaGamePassNft__factory } from "./IKtaGamePassNft__factory";
export { KtaGamePassNft__factory } from "./KtaGamePassNft__factory";
