/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Coordinates {
  export type CoordinateStruct = { _x: BigNumberish; _y: BigNumberish };

  export type CoordinateStructOutput = [_x: bigint, _y: bigint] & {
    _x: bigint;
    _y: bigint;
  };
}

export declare namespace Timers {
  export type BlockNumberStruct = { _at: BigNumberish };

  export type BlockNumberStructOutput = [_at: bigint] & { _at: bigint };
}

export declare namespace IKillThemAll {
  export type WarStruct = {
    attackerTownId: BigNumberish;
    defenderTownId: BigNumberish;
    attackableAt: Timers.BlockNumberStruct;
    expiredAt: Timers.BlockNumberStruct;
  };

  export type WarStructOutput = [
    attackerTownId: bigint,
    defenderTownId: bigint,
    attackableAt: Timers.BlockNumberStructOutput,
    expiredAt: Timers.BlockNumberStructOutput
  ] & {
    attackerTownId: bigint;
    defenderTownId: bigint;
    attackableAt: Timers.BlockNumberStructOutput;
    expiredAt: Timers.BlockNumberStructOutput;
  };

  export type GamePassStruct = {
    pass: AddressLike;
    price: BigNumberish;
    startBlock: BigNumberish;
    endBlock: BigNumberish;
    phaseLimits: BigNumberish[];
  };

  export type GamePassStructOutput = [
    pass: string,
    price: bigint,
    startBlock: bigint,
    endBlock: bigint,
    phaseLimits: bigint[]
  ] & {
    pass: string;
    price: bigint;
    startBlock: bigint;
    endBlock: bigint;
    phaseLimits: bigint[];
  };

  export type TownLevelStruct = { maxUser: BigNumberish };

  export type TownLevelStructOutput = [maxUser: bigint] & { maxUser: bigint };

  export type UserLevelStruct = { min: BigNumberish; max: BigNumberish };

  export type UserLevelStructOutput = [min: bigint, max: bigint] & {
    min: bigint;
    max: bigint;
  };

  export type MaxSettingStruct = {
    health: BigNumberish;
    mana: BigNumberish;
    energy: BigNumberish;
    armor: BigNumberish;
    teleportDistance: BigNumberish;
    killArmorRewardLimit: BigNumberish;
    safeTownDistance: BigNumberish;
    safeTownDifference: BigNumberish;
    safeZoneDistance: BigNumberish;
    safeZoneDifference: BigNumberish;
    attackDistance: BigNumberish;
    levelDifference: BigNumberish;
  };

  export type MaxSettingStructOutput = [
    health: bigint,
    mana: bigint,
    energy: bigint,
    armor: bigint,
    teleportDistance: bigint,
    killArmorRewardLimit: bigint,
    safeTownDistance: bigint,
    safeTownDifference: bigint,
    safeZoneDistance: bigint,
    safeZoneDifference: bigint,
    attackDistance: bigint,
    levelDifference: bigint
  ] & {
    health: bigint;
    mana: bigint;
    energy: bigint;
    armor: bigint;
    teleportDistance: bigint;
    killArmorRewardLimit: bigint;
    safeTownDistance: bigint;
    safeTownDifference: bigint;
    safeZoneDistance: bigint;
    safeZoneDifference: bigint;
    attackDistance: bigint;
    levelDifference: bigint;
  };

  export type PriceSettingStruct = {
    health: BigNumberish;
    mana: BigNumberish;
    energy: BigNumberish;
    armor: BigNumberish;
    revive: BigNumberish;
    register: BigNumberish;
    teleport: BigNumberish;
    createTown: BigNumberish;
    settleTown: BigNumberish;
    teleportToTown: BigNumberish;
    prepareAttack: BigNumberish;
    prepareDefend: BigNumberish;
  };

  export type PriceSettingStructOutput = [
    health: bigint,
    mana: bigint,
    energy: bigint,
    armor: bigint,
    revive: bigint,
    register: bigint,
    teleport: bigint,
    createTown: bigint,
    settleTown: bigint,
    teleportToTown: bigint,
    prepareAttack: bigint,
    prepareDefend: bigint
  ] & {
    health: bigint;
    mana: bigint;
    energy: bigint;
    armor: bigint;
    revive: bigint;
    register: bigint;
    teleport: bigint;
    createTown: bigint;
    settleTown: bigint;
    teleportToTown: bigint;
    prepareAttack: bigint;
    prepareDefend: bigint;
  };

  export type RateSettingStruct = {
    getHealth: BigNumberish;
    getMana: BigNumberish;
    getEnergy: BigNumberish;
    registerReferralReward: BigNumberish;
    armorAbsorption: BigNumberish;
    attack: BigNumberish;
    movement: BigNumberish;
  };

  export type RateSettingStructOutput = [
    getHealth: bigint,
    getMana: bigint,
    getEnergy: bigint,
    registerReferralReward: bigint,
    armorAbsorption: bigint,
    attack: bigint,
    movement: bigint
  ] & {
    getHealth: bigint;
    getMana: bigint;
    getEnergy: bigint;
    registerReferralReward: bigint;
    armorAbsorption: bigint;
    attack: bigint;
    movement: bigint;
  };

  export type TimeSettingStruct = {
    revive: BigNumberish;
    teleport: BigNumberish;
    teleportToTown: BigNumberish;
    attackableAt: BigNumberish;
    warExpiredAt: BigNumberish;
    protectionAt: BigNumberish;
    prepareToAttack: BigNumberish;
  };

  export type TimeSettingStructOutput = [
    revive: bigint,
    teleport: bigint,
    teleportToTown: bigint,
    attackableAt: bigint,
    warExpiredAt: bigint,
    protectionAt: bigint,
    prepareToAttack: bigint
  ] & {
    revive: bigint;
    teleport: bigint;
    teleportToTown: bigint;
    attackableAt: bigint;
    warExpiredAt: bigint;
    protectionAt: bigint;
    prepareToAttack: bigint;
  };

  export type MinSettingStruct = {
    levelToCreateTown: BigNumberish;
    townAreaRadius: BigNumberish;
  };

  export type MinSettingStructOutput = [
    levelToCreateTown: bigint,
    townAreaRadius: bigint
  ] & { levelToCreateTown: bigint; townAreaRadius: bigint };

  export type ExpSettingStruct = {
    kill: BigNumberish;
    referrerKill: BigNumberish;
  };

  export type ExpSettingStructOutput = [kill: bigint, referrerKill: bigint] & {
    kill: bigint;
    referrerKill: bigint;
  };

  export type MultiplierSettingStruct = {
    attack: BigNumberish;
    resistance: BigNumberish;
  };

  export type MultiplierSettingStructOutput = [
    attack: bigint,
    resistance: bigint
  ] & { attack: bigint; resistance: bigint };

  export type SettingStruct = {
    max: IKillThemAll.MaxSettingStruct;
    price: IKillThemAll.PriceSettingStruct;
    rate: IKillThemAll.RateSettingStruct;
    time: IKillThemAll.TimeSettingStruct;
    min: IKillThemAll.MinSettingStruct;
    exp: IKillThemAll.ExpSettingStruct;
    multiplier: IKillThemAll.MultiplierSettingStruct;
    numberDigits: BigNumberish;
  };

  export type SettingStructOutput = [
    max: IKillThemAll.MaxSettingStructOutput,
    price: IKillThemAll.PriceSettingStructOutput,
    rate: IKillThemAll.RateSettingStructOutput,
    time: IKillThemAll.TimeSettingStructOutput,
    min: IKillThemAll.MinSettingStructOutput,
    exp: IKillThemAll.ExpSettingStructOutput,
    multiplier: IKillThemAll.MultiplierSettingStructOutput,
    numberDigits: bigint
  ] & {
    max: IKillThemAll.MaxSettingStructOutput;
    price: IKillThemAll.PriceSettingStructOutput;
    rate: IKillThemAll.RateSettingStructOutput;
    time: IKillThemAll.TimeSettingStructOutput;
    min: IKillThemAll.MinSettingStructOutput;
    exp: IKillThemAll.ExpSettingStructOutput;
    multiplier: IKillThemAll.MultiplierSettingStructOutput;
    numberDigits: bigint;
  };
}

export interface IKillThemAllInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addGamePass"
      | "attack"
      | "buy"
      | "buyGamePass"
      | "changeName"
      | "changeTownRecruitment"
      | "claimGamePassReward"
      | "createTown"
      | "createTownLevel"
      | "createUserLevel"
      | "declareWar"
      | "exileCitizen"
      | "get"
      | "getAddressesByCoordinate"
      | "joinTown"
      | "leaveTown"
      | "move"
      | "prepareToConditionBonus"
      | "register"
      | "revive"
      | "setConditionBonus"
      | "settleTown"
      | "teleport"
      | "teleportToTown"
      | "updateSettings"
      | "voyageTown"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LevelUp"
      | "TownCreated"
      | "TownDisbanded"
      | "TownRecruitmentUpdated"
      | "TownSettled"
      | "TownVoyaged"
      | "UserArmorBroken"
      | "UserAttacked"
      | "UserBought"
      | "UserBoughtGamePass"
      | "UserClaimedGamePassPhase"
      | "UserExitFromTown"
      | "UserGot"
      | "UserJoinedTown"
      | "UserKilled"
      | "UserMissed"
      | "UserMoved"
      | "UserPrepared"
      | "UserRegistered"
      | "WarDeclared"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addGamePass",
    values: [IKillThemAll.GamePassStruct]
  ): string;
  encodeFunctionData(functionFragment: "attack", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyGamePass",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeName",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeTownRecruitment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimGamePassReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTown",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTownLevel",
    values: [IKillThemAll.TownLevelStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createUserLevel",
    values: [IKillThemAll.UserLevelStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "declareWar",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exileCitizen",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "get", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getAddressesByCoordinate",
    values: [Coordinates.CoordinateStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "joinTown",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "leaveTown", values?: undefined): string;
  encodeFunctionData(functionFragment: "move", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "prepareToConditionBonus",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "revive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setConditionBonus",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleTown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teleport",
    values: [Coordinates.CoordinateStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "teleportToTown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSettings",
    values: [IKillThemAll.SettingStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "voyageTown",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addGamePass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyGamePass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changeName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeTownRecruitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimGamePassReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTown", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createTownLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createUserLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "declareWar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exileCitizen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressesByCoordinate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinTown", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "leaveTown", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "move", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "prepareToConditionBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setConditionBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settleTown", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "teleport", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "teleportToTown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voyageTown", data: BytesLike): Result;
}

export namespace LevelUpEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TownCreatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TownDisbandedEvent {
  export type InputTuple = [townId: BigNumberish];
  export type OutputTuple = [townId: bigint];
  export interface OutputObject {
    townId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TownRecruitmentUpdatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TownSettledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TownVoyagedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserArmorBrokenEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserAttackedEvent {
  export type InputTuple = [
    defender: AddressLike,
    healthDamage: BigNumberish,
    armorDamage: BigNumberish
  ];
  export type OutputTuple = [
    defender: string,
    healthDamage: bigint,
    armorDamage: bigint
  ];
  export interface OutputObject {
    defender: string;
    healthDamage: bigint;
    armorDamage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserBoughtEvent {
  export type InputTuple = [
    something: BigNumberish,
    to: AddressLike,
    amount: BigNumberish,
    buyer: AddressLike
  ];
  export type OutputTuple = [
    something: bigint,
    to: string,
    amount: bigint,
    buyer: string
  ];
  export interface OutputObject {
    something: bigint;
    to: string;
    amount: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserBoughtGamePassEvent {
  export type InputTuple = [gamePassId: BigNumberish];
  export type OutputTuple = [gamePassId: bigint];
  export interface OutputObject {
    gamePassId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserClaimedGamePassPhaseEvent {
  export type InputTuple = [
    gamePassId: BigNumberish,
    gamePassPhase: BigNumberish
  ];
  export type OutputTuple = [gamePassId: bigint, gamePassPhase: bigint];
  export interface OutputObject {
    gamePassId: bigint;
    gamePassPhase: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserExitFromTownEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserGotEvent {
  export type InputTuple = [something: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [something: bigint, amount: bigint];
  export interface OutputObject {
    something: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserJoinedTownEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserKilledEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserMissedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserMovedEvent {
  export type InputTuple = [
    user: AddressLike,
    oldCoordinate: Coordinates.CoordinateStruct,
    newCoordinate: Coordinates.CoordinateStruct
  ];
  export type OutputTuple = [
    user: string,
    oldCoordinate: Coordinates.CoordinateStructOutput,
    newCoordinate: Coordinates.CoordinateStructOutput
  ];
  export interface OutputObject {
    user: string;
    oldCoordinate: Coordinates.CoordinateStructOutput;
    newCoordinate: Coordinates.CoordinateStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserPreparedEvent {
  export type InputTuple = [to: BigNumberish, addressesHash: BytesLike];
  export type OutputTuple = [to: bigint, addressesHash: string];
  export interface OutputObject {
    to: bigint;
    addressesHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WarDeclaredEvent {
  export type InputTuple = [war: IKillThemAll.WarStruct];
  export type OutputTuple = [war: IKillThemAll.WarStructOutput];
  export interface OutputObject {
    war: IKillThemAll.WarStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IKillThemAll extends BaseContract {
  contractName: "IKillThemAll";

  connect(runner?: ContractRunner | null): IKillThemAll;
  waitForDeployment(): Promise<this>;

  interface: IKillThemAllInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addGamePass: TypedContractMethod<
    [gamePass: IKillThemAll.GamePassStruct],
    [void],
    "nonpayable"
  >;

  attack: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  buy: TypedContractMethod<
    [buy_: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  buyGamePass: TypedContractMethod<[], [void], "nonpayable">;

  changeName: TypedContractMethod<[name: BytesLike], [void], "nonpayable">;

  changeTownRecruitment: TypedContractMethod<[], [void], "nonpayable">;

  claimGamePassReward: TypedContractMethod<
    [phase: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTown: TypedContractMethod<
    [name: BytesLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTownLevel: TypedContractMethod<
    [townLevel: IKillThemAll.TownLevelStruct],
    [void],
    "nonpayable"
  >;

  createUserLevel: TypedContractMethod<
    [userLevel: IKillThemAll.UserLevelStruct],
    [void],
    "nonpayable"
  >;

  declareWar: TypedContractMethod<[townId: BigNumberish], [void], "nonpayable">;

  exileCitizen: TypedContractMethod<
    [citizen_: AddressLike],
    [void],
    "nonpayable"
  >;

  get: TypedContractMethod<[get_: BigNumberish], [void], "nonpayable">;

  getAddressesByCoordinate: TypedContractMethod<
    [coordinate: Coordinates.CoordinateStruct],
    [string[]],
    "view"
  >;

  joinTown: TypedContractMethod<[townId: BigNumberish], [void], "nonpayable">;

  leaveTown: TypedContractMethod<[], [void], "nonpayable">;

  move: TypedContractMethod<[direction: BigNumberish], [void], "nonpayable">;

  prepareToConditionBonus: TypedContractMethod<
    [to: BigNumberish, target: AddressLike],
    [void],
    "nonpayable"
  >;

  register: TypedContractMethod<
    [name: BytesLike, referrer: AddressLike],
    [void],
    "nonpayable"
  >;

  revive: TypedContractMethod<[], [void], "nonpayable">;

  setConditionBonus: TypedContractMethod<
    [to: BigNumberish, addressesHash: BytesLike, random: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleTown: TypedContractMethod<[], [void], "nonpayable">;

  teleport: TypedContractMethod<
    [coordinate: Coordinates.CoordinateStruct],
    [void],
    "nonpayable"
  >;

  teleportToTown: TypedContractMethod<[], [void], "nonpayable">;

  updateSettings: TypedContractMethod<
    [settings_: IKillThemAll.SettingStruct],
    [void],
    "nonpayable"
  >;

  voyageTown: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addGamePass"
  ): TypedContractMethod<
    [gamePass: IKillThemAll.GamePassStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attack"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [buy_: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyGamePass"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeName"
  ): TypedContractMethod<[name: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeTownRecruitment"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimGamePassReward"
  ): TypedContractMethod<[phase: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTown"
  ): TypedContractMethod<
    [name: BytesLike, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTownLevel"
  ): TypedContractMethod<
    [townLevel: IKillThemAll.TownLevelStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createUserLevel"
  ): TypedContractMethod<
    [userLevel: IKillThemAll.UserLevelStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "declareWar"
  ): TypedContractMethod<[townId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "exileCitizen"
  ): TypedContractMethod<[citizen_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "get"
  ): TypedContractMethod<[get_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAddressesByCoordinate"
  ): TypedContractMethod<
    [coordinate: Coordinates.CoordinateStruct],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinTown"
  ): TypedContractMethod<[townId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "leaveTown"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "move"
  ): TypedContractMethod<[direction: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "prepareToConditionBonus"
  ): TypedContractMethod<
    [to: BigNumberish, target: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [name: BytesLike, referrer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revive"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setConditionBonus"
  ): TypedContractMethod<
    [to: BigNumberish, addressesHash: BytesLike, random: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleTown"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "teleport"
  ): TypedContractMethod<
    [coordinate: Coordinates.CoordinateStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "teleportToTown"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSettings"
  ): TypedContractMethod<
    [settings_: IKillThemAll.SettingStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voyageTown"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "LevelUp"
  ): TypedContractEvent<
    LevelUpEvent.InputTuple,
    LevelUpEvent.OutputTuple,
    LevelUpEvent.OutputObject
  >;
  getEvent(
    key: "TownCreated"
  ): TypedContractEvent<
    TownCreatedEvent.InputTuple,
    TownCreatedEvent.OutputTuple,
    TownCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TownDisbanded"
  ): TypedContractEvent<
    TownDisbandedEvent.InputTuple,
    TownDisbandedEvent.OutputTuple,
    TownDisbandedEvent.OutputObject
  >;
  getEvent(
    key: "TownRecruitmentUpdated"
  ): TypedContractEvent<
    TownRecruitmentUpdatedEvent.InputTuple,
    TownRecruitmentUpdatedEvent.OutputTuple,
    TownRecruitmentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TownSettled"
  ): TypedContractEvent<
    TownSettledEvent.InputTuple,
    TownSettledEvent.OutputTuple,
    TownSettledEvent.OutputObject
  >;
  getEvent(
    key: "TownVoyaged"
  ): TypedContractEvent<
    TownVoyagedEvent.InputTuple,
    TownVoyagedEvent.OutputTuple,
    TownVoyagedEvent.OutputObject
  >;
  getEvent(
    key: "UserArmorBroken"
  ): TypedContractEvent<
    UserArmorBrokenEvent.InputTuple,
    UserArmorBrokenEvent.OutputTuple,
    UserArmorBrokenEvent.OutputObject
  >;
  getEvent(
    key: "UserAttacked"
  ): TypedContractEvent<
    UserAttackedEvent.InputTuple,
    UserAttackedEvent.OutputTuple,
    UserAttackedEvent.OutputObject
  >;
  getEvent(
    key: "UserBought"
  ): TypedContractEvent<
    UserBoughtEvent.InputTuple,
    UserBoughtEvent.OutputTuple,
    UserBoughtEvent.OutputObject
  >;
  getEvent(
    key: "UserBoughtGamePass"
  ): TypedContractEvent<
    UserBoughtGamePassEvent.InputTuple,
    UserBoughtGamePassEvent.OutputTuple,
    UserBoughtGamePassEvent.OutputObject
  >;
  getEvent(
    key: "UserClaimedGamePassPhase"
  ): TypedContractEvent<
    UserClaimedGamePassPhaseEvent.InputTuple,
    UserClaimedGamePassPhaseEvent.OutputTuple,
    UserClaimedGamePassPhaseEvent.OutputObject
  >;
  getEvent(
    key: "UserExitFromTown"
  ): TypedContractEvent<
    UserExitFromTownEvent.InputTuple,
    UserExitFromTownEvent.OutputTuple,
    UserExitFromTownEvent.OutputObject
  >;
  getEvent(
    key: "UserGot"
  ): TypedContractEvent<
    UserGotEvent.InputTuple,
    UserGotEvent.OutputTuple,
    UserGotEvent.OutputObject
  >;
  getEvent(
    key: "UserJoinedTown"
  ): TypedContractEvent<
    UserJoinedTownEvent.InputTuple,
    UserJoinedTownEvent.OutputTuple,
    UserJoinedTownEvent.OutputObject
  >;
  getEvent(
    key: "UserKilled"
  ): TypedContractEvent<
    UserKilledEvent.InputTuple,
    UserKilledEvent.OutputTuple,
    UserKilledEvent.OutputObject
  >;
  getEvent(
    key: "UserMissed"
  ): TypedContractEvent<
    UserMissedEvent.InputTuple,
    UserMissedEvent.OutputTuple,
    UserMissedEvent.OutputObject
  >;
  getEvent(
    key: "UserMoved"
  ): TypedContractEvent<
    UserMovedEvent.InputTuple,
    UserMovedEvent.OutputTuple,
    UserMovedEvent.OutputObject
  >;
  getEvent(
    key: "UserPrepared"
  ): TypedContractEvent<
    UserPreparedEvent.InputTuple,
    UserPreparedEvent.OutputTuple,
    UserPreparedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "WarDeclared"
  ): TypedContractEvent<
    WarDeclaredEvent.InputTuple,
    WarDeclaredEvent.OutputTuple,
    WarDeclaredEvent.OutputObject
  >;

  filters: {
    "LevelUp(address)": TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;
    LevelUp: TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;

    "TownCreated()": TypedContractEvent<
      TownCreatedEvent.InputTuple,
      TownCreatedEvent.OutputTuple,
      TownCreatedEvent.OutputObject
    >;
    TownCreated: TypedContractEvent<
      TownCreatedEvent.InputTuple,
      TownCreatedEvent.OutputTuple,
      TownCreatedEvent.OutputObject
    >;

    "TownDisbanded(uint256)": TypedContractEvent<
      TownDisbandedEvent.InputTuple,
      TownDisbandedEvent.OutputTuple,
      TownDisbandedEvent.OutputObject
    >;
    TownDisbanded: TypedContractEvent<
      TownDisbandedEvent.InputTuple,
      TownDisbandedEvent.OutputTuple,
      TownDisbandedEvent.OutputObject
    >;

    "TownRecruitmentUpdated()": TypedContractEvent<
      TownRecruitmentUpdatedEvent.InputTuple,
      TownRecruitmentUpdatedEvent.OutputTuple,
      TownRecruitmentUpdatedEvent.OutputObject
    >;
    TownRecruitmentUpdated: TypedContractEvent<
      TownRecruitmentUpdatedEvent.InputTuple,
      TownRecruitmentUpdatedEvent.OutputTuple,
      TownRecruitmentUpdatedEvent.OutputObject
    >;

    "TownSettled()": TypedContractEvent<
      TownSettledEvent.InputTuple,
      TownSettledEvent.OutputTuple,
      TownSettledEvent.OutputObject
    >;
    TownSettled: TypedContractEvent<
      TownSettledEvent.InputTuple,
      TownSettledEvent.OutputTuple,
      TownSettledEvent.OutputObject
    >;

    "TownVoyaged()": TypedContractEvent<
      TownVoyagedEvent.InputTuple,
      TownVoyagedEvent.OutputTuple,
      TownVoyagedEvent.OutputObject
    >;
    TownVoyaged: TypedContractEvent<
      TownVoyagedEvent.InputTuple,
      TownVoyagedEvent.OutputTuple,
      TownVoyagedEvent.OutputObject
    >;

    "UserArmorBroken()": TypedContractEvent<
      UserArmorBrokenEvent.InputTuple,
      UserArmorBrokenEvent.OutputTuple,
      UserArmorBrokenEvent.OutputObject
    >;
    UserArmorBroken: TypedContractEvent<
      UserArmorBrokenEvent.InputTuple,
      UserArmorBrokenEvent.OutputTuple,
      UserArmorBrokenEvent.OutputObject
    >;

    "UserAttacked(address,uint256,uint256)": TypedContractEvent<
      UserAttackedEvent.InputTuple,
      UserAttackedEvent.OutputTuple,
      UserAttackedEvent.OutputObject
    >;
    UserAttacked: TypedContractEvent<
      UserAttackedEvent.InputTuple,
      UserAttackedEvent.OutputTuple,
      UserAttackedEvent.OutputObject
    >;

    "UserBought(uint8,address,uint256,address)": TypedContractEvent<
      UserBoughtEvent.InputTuple,
      UserBoughtEvent.OutputTuple,
      UserBoughtEvent.OutputObject
    >;
    UserBought: TypedContractEvent<
      UserBoughtEvent.InputTuple,
      UserBoughtEvent.OutputTuple,
      UserBoughtEvent.OutputObject
    >;

    "UserBoughtGamePass(uint256)": TypedContractEvent<
      UserBoughtGamePassEvent.InputTuple,
      UserBoughtGamePassEvent.OutputTuple,
      UserBoughtGamePassEvent.OutputObject
    >;
    UserBoughtGamePass: TypedContractEvent<
      UserBoughtGamePassEvent.InputTuple,
      UserBoughtGamePassEvent.OutputTuple,
      UserBoughtGamePassEvent.OutputObject
    >;

    "UserClaimedGamePassPhase(uint256,uint256)": TypedContractEvent<
      UserClaimedGamePassPhaseEvent.InputTuple,
      UserClaimedGamePassPhaseEvent.OutputTuple,
      UserClaimedGamePassPhaseEvent.OutputObject
    >;
    UserClaimedGamePassPhase: TypedContractEvent<
      UserClaimedGamePassPhaseEvent.InputTuple,
      UserClaimedGamePassPhaseEvent.OutputTuple,
      UserClaimedGamePassPhaseEvent.OutputObject
    >;

    "UserExitFromTown(address)": TypedContractEvent<
      UserExitFromTownEvent.InputTuple,
      UserExitFromTownEvent.OutputTuple,
      UserExitFromTownEvent.OutputObject
    >;
    UserExitFromTown: TypedContractEvent<
      UserExitFromTownEvent.InputTuple,
      UserExitFromTownEvent.OutputTuple,
      UserExitFromTownEvent.OutputObject
    >;

    "UserGot(uint8,uint256)": TypedContractEvent<
      UserGotEvent.InputTuple,
      UserGotEvent.OutputTuple,
      UserGotEvent.OutputObject
    >;
    UserGot: TypedContractEvent<
      UserGotEvent.InputTuple,
      UserGotEvent.OutputTuple,
      UserGotEvent.OutputObject
    >;

    "UserJoinedTown()": TypedContractEvent<
      UserJoinedTownEvent.InputTuple,
      UserJoinedTownEvent.OutputTuple,
      UserJoinedTownEvent.OutputObject
    >;
    UserJoinedTown: TypedContractEvent<
      UserJoinedTownEvent.InputTuple,
      UserJoinedTownEvent.OutputTuple,
      UserJoinedTownEvent.OutputObject
    >;

    "UserKilled(address)": TypedContractEvent<
      UserKilledEvent.InputTuple,
      UserKilledEvent.OutputTuple,
      UserKilledEvent.OutputObject
    >;
    UserKilled: TypedContractEvent<
      UserKilledEvent.InputTuple,
      UserKilledEvent.OutputTuple,
      UserKilledEvent.OutputObject
    >;

    "UserMissed()": TypedContractEvent<
      UserMissedEvent.InputTuple,
      UserMissedEvent.OutputTuple,
      UserMissedEvent.OutputObject
    >;
    UserMissed: TypedContractEvent<
      UserMissedEvent.InputTuple,
      UserMissedEvent.OutputTuple,
      UserMissedEvent.OutputObject
    >;

    "UserMoved(address,tuple,tuple)": TypedContractEvent<
      UserMovedEvent.InputTuple,
      UserMovedEvent.OutputTuple,
      UserMovedEvent.OutputObject
    >;
    UserMoved: TypedContractEvent<
      UserMovedEvent.InputTuple,
      UserMovedEvent.OutputTuple,
      UserMovedEvent.OutputObject
    >;

    "UserPrepared(uint8,bytes32)": TypedContractEvent<
      UserPreparedEvent.InputTuple,
      UserPreparedEvent.OutputTuple,
      UserPreparedEvent.OutputObject
    >;
    UserPrepared: TypedContractEvent<
      UserPreparedEvent.InputTuple,
      UserPreparedEvent.OutputTuple,
      UserPreparedEvent.OutputObject
    >;

    "UserRegistered()": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;

    "WarDeclared(tuple)": TypedContractEvent<
      WarDeclaredEvent.InputTuple,
      WarDeclaredEvent.OutputTuple,
      WarDeclaredEvent.OutputObject
    >;
    WarDeclared: TypedContractEvent<
      WarDeclaredEvent.InputTuple,
      WarDeclaredEvent.OutputTuple,
      WarDeclaredEvent.OutputObject
    >;
  };
}
