/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chat from "./chat";
export type { chat };
import type * as pass from "./pass";
export type { pass };
import type * as token from "./token";
export type { token };
export type { IKillThemAll } from "./IKillThemAll";
export type { KillThemAll } from "./KillThemAll";
