name: cd

on:
  push:
    branches:
      - main
      - master
      - bingo
  pull_request:
    branches:
      - main
      - master
      - bingo
  workflow_dispatch:

env:
  NUXT_DRAWN_NUMBERS_ADDITIONAL_TIME_IN_SEC: ${{ vars.NUXT_DRAWN_NUMBERS_ADDITIONAL_TIME_IN_SEC }}
  NUXT_DRAWN_NUMBERS_INTERVAL_IN_SEC: ${{ vars.NUXT_DRAWN_NUMBERS_INTERVAL_IN_SEC }}
  NUXT_APP_URL: ${{ vars.NUXT_APP_URL }}
  NUXT_CHAIN_BLOCK_TIME_IN_SEC: ${{ vars.NUXT_CHAIN_BLOCK_TIME_IN_SEC }}
  NUXT_CHAIN: ${{ vars.NUXT_CHAIN }}
  NUXT_CHAIN_EXTEND_EXPLORER_URLS: ${{ vars.NUXT_CHAIN_EXTEND_EXPLORER_URLS }}
  NUXT_BINGO_CONTRACT_ADDRESS: ${{ vars.NUXT_BINGO_CONTRACT_ADDRESS }}
  NUXT_PUBLIC_RPC_URLS: ${{ vars.NUXT_PUBLIC_RPC_URLS }}
  NUXT_OZ_DEFENDER_RELAYER_WEBHOOK_URL: ${{ vars.NUXT_OZ_DEFENDER_RELAYER_WEBHOOK_URL }}
  NUXT_OZ_DEFENDER_RELAYER_MESSAGE: ${{ vars.NUXT_OZ_DEFENDER_RELAYER_MESSAGE }}
  NUXT_REOWN_APPKIT_PROJECT_ID: ${{ vars.NUXT_REOWN_APPKIT_PROJECT_ID }}

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Load environment variables
        run: |
          export $(cat .env | xargs)

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            src
            nuxt.config.ts
            package.json
            yarn.lock

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies with dev deps
        run: yarn install --production=false

      - name: Build
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          publish_branch: gh-pages
